### ISSUE TITLE
hi there

### ISSUE THREAD

**Issue by samleemc** [mobiraft/AwesomeSplash#2]
If I already built the app, how can I still add the splash screen before the ContentView is loaded? Especially there is a Environment object being loaded in the SenceDelegate....

Thanks!

**Comment by hardikjparmar** [comment]
Hey @samleemc, 
You can simply open SplashView from the SceneDelegate or New SwiftUI App class directly and then open your desired View (ContentView) from SplashView. If you need more guidance, please share your code so that we can help you better.

**Comment by samleemc** [comment]
Thanks, I got it figure out, one way or another ... lol
